import { IProductItem, IProductCategory } from "@/models/product-type";

export const mockProducts: IProductItem[] = [
  {
    id: "1",
    title: "Samsung Galaxy S22 Ultra",
    description: "Description 1",
    image: "thumb-avocado.png",
    currency: "ZK",
    amount: 9.5,
    category: {
      id: 3,
      slug: "electronics",
      name: "Electronics",
    },
    quantity: 6,
    rating: 4.5,
  },
  {
    id: "2",
    title: "Iphone 15 Pro",
    description: "Description 2",
    image: "thumb-bananas.png",
    currency: "ZK",
    amount: 19.25,
    category: {
      id: 2,
      slug: "clothing",
      name: "Clothing",
    },
    quantity: 3,
    rating: 4.5,
  },
  {
    id: "3",
    title: "KitchenAid Classic Stand Mixer",
    description: "Description 3",
    image: "thumb-biscuits.png",
    currency: "ZK",
    amount: 38.75,
    category: {
      id: 4,
      slug: "home-cleaning",
      name: "Home & Cleaning",
    },
    quantity: 4,
    rating: 4.5,
  },
  {
    id: "4",
    title: "Cuisinart 15-Piece Stainless Steel Cookware Set",
    description: "Description 4",
    image: "thumb-cucumber.png",
    currency: "ZK",
    amount: 48.5,
    category: {
      id: 5,
      slug: "furniture",
      name: "Furniture",
    },
    quantity: 1,
    rating: 4.5,
  },
  {
    id: "5",
    title: "Breville One Hand Blender",
    description: "Description 5",
    image: "thumb-orange-juice.png",
    currency: "ZK",
    amount: 68.99,
    category: {
      id: 6,
      slug: "groceries",
      name: "Groceries",
    },
    quantity: 10,
    rating: 4.5,
  },
  {
    id: "6",
    title: "Amazon Echo Show 10",
    description: "Description 6",
    image: "thumb-tomatoes.png",
    currency: "ZK",
    amount: 79.5,
    category: {
      id: 7,
      slug: "food",
      name: "Food",
    },
    quantity: 5,
    rating: 4.5,
  },
  {
    id: "7",
    title: "Sony Bravia 55-inch 4K UHD Smart TV",
    description: "Description 7",
    image: "thumb-milk.png",
    currency: "ZK",
    amount: 97.25,
    category: {
      id: 3,
      slug: "electronics",
      name: "Electronics",
    },
    quantity: 12,
    rating: 4.5,
  },
  {
    id: "8",
    title: "Apple AirPods Pro",
    description: "Description 8",
    image: "thumb-raspberries.png",
    currency: "ZK",
    amount: 127.5,
    category: {
      id: 6,
      slug: "groceries",
      name: "Groceries",
    },
    quantity: 7,
    rating: 4.5,
  },
];
