import { IProductItem } from "@/models/product-type";

export const mockProducts: IProductItem[] = [
  {
    id: "1",
    title: "Samsung Galaxy S22 Ultra",
    description: "Description 1",
    image: "thumb-avocado.png",
    currency: "ZK",
    amount: "9.50",
    quantity: 1,
    rating: 4.5,
    isFavorite: false,
  },
  {
    id: "2",
    title: "Iphone 15 Pro",
    description: "Description 2",
    image: "thumb-bananas.png",
    currency: "ZK",
    amount: "19.25",
    quantity: 2,
    rating: 4.5,
    isFavorite: true,
  },
  {
    id: "3",
    title: "KitchenAid Classic Stand Mixer",
    description: "Description 3",
    image: "thumb-biscuits.png",
    currency: "ZK",
    amount: "38.75",
    quantity: 1,
    rating: 4.5,
    isFavorite: false,
  },
  {
    id: "4",
    title: "Cuisinart 15-Piece Stainless Steel Cookware Set",
    description: "Description 4",
    image: "thumb-cucumber.png",
    currency: "ZK",
    amount: "48.50",
    quantity: 1,
    rating: 4.5,
    isFavorite: false,
  },
  {
    id: "5",
    title: "Breville One Hand Blender",
    description: "Description 5",
    image: "thumb-orange-juice.png",
    currency: "ZK",
    amount: "68.99",
    quantity: 1,
    rating: 4.5,
    isFavorite: false,
  },
  {
    id: "6",
    title: "Amazon Echo Show 10",
    description: "Description 6",
    image: "thumb-tomatoes.png",
    currency: "ZK",
    amount: "79.50",
    quantity: 1,
    rating: 4.5,
    isFavorite: true,
  },
  {
    id: "7",
    title: "Sony Bravia 55-inch 4K UHD Smart TV",
    description: "Description 7",
    image: "thumb-milk.png",
    currency: "ZK",
    amount: "97.25",
    quantity: 2,
    rating: 4.5,
    isFavorite: false,
  },
  {
    id: "8",
    title: "Apple AirPods Pro",
    description: "Description 8",
    image: "thumb-raspberries.png",
    currency: "ZK",
    amount: "127.50",
    quantity: 2,
    rating: 4.5,
    isFavorite: true,
  },
];
